name: vectorized2d
channels:
- numba
- conda-forge
- defaults
dependencies:
- blas
- icc_rt
- intel-openmp
- mkl
- mkl_fft
- mkl_random
- numba
- numpy
- pip
- pytest
- pytest-cov
- python=3.8
- setuptools
- pip:
  - fast-enum==1.3.0
